---

- name: Connection tracking?
  sysctl:
    name: net.netfilter.nf_conntrack_tcp_be_liberal
    value: 1
    state: present
    sysctl_set: yes
    reload: yes

- name: Установка firewall
  community.general.ufw:
    state: enabled

- name: Rezervniy kanal
  community.general.ufw:
    rule: allow
    src: 10.10.10.10
    port: '22'
    proto: tcp
    

- name: настройка правил по умолчанию.
  community.general.ufw:
    default: deny 
    direction: incoming
    






